# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-17 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manavmitra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=500)),
                ('image_upload', models.ImageField(upload_to='gujarati/media')),
                ('image', models.TextField()),
                ('embed', models.TextField()),
                ('video', models.TextField()),
                ('article', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Epaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_paper_name', models.CharField(max_length=50)),
                ('e_paper', models.FileField(upload_to='gujarati/Epaper')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trailer_name', models.CharField(max_length=50)),
                ('trailer_url', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='E_paper',
        ),
        migrations.RemoveField(
            model_name='news',
            name='category',
        ),
        migrations.RemoveField(
            model_name='news',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manavmitra.Category'),
        ),
    ]
