# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-19 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manavmitra', '0002_auto_20170717_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='embed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='video',
            field=models.TextField(blank=True, null=True),
        ),
    ]
