# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-19 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manavmitra', '0003_auto_20170719_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
