# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-19 17:27
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('manavmitra', '0004_auto_20170719_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='article',
            field=tinymce.models.HTMLField(),
        ),
    ]
