# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-19 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manavmitra', '0005_auto_20170719_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='article',
            field=models.CharField(max_length=5000),
        ),
    ]
