# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-31 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manavmitra', '0013_auto_20170728_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='articlemain',
            field=models.TextField(blank=True, null=True),
        ),
    ]
