# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-19 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=500)),
                ('image_upload', models.ImageField(upload_to='gujarati/media')),
                ('article', tinymce.models.HTMLField()),
                ('video', models.TextField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('embed', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Epaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_paper_name', models.CharField(max_length=50)),
                ('e_paper', models.FileField(upload_to='gujarati/Epaper')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trailer_name', models.CharField(max_length=50)),
                ('trailer_url', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hindi.Category'),
        ),
    ]
