# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-21 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hindi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='article',
            field=models.TextField(),
        ),
    ]
