# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-21 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hindi', '0002_auto_20170721_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='embed',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
        migrations.AlterField(
            model_name='blog',
            name='video',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
