# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-01 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hindi', '0009_auto_20170801_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image_upload',
            field=models.ImageField(upload_to=b'hindi/media'),
        ),
        migrations.AlterField(
            model_name='epaper',
            name='e_paper',
            field=models.FileField(upload_to=b'hindi/Epaper'),
        ),
    ]
